### ISSUE TITLE
To support segmentation task

### ISSUE THREAD

**Issue by hanin97** [gatsby2016/Augmentation-PyTorch-Transforms#1]
Hi gatsby,
    Your code is so cool, but, can you update it to support segmentation task?

**Comment by gatsby2016** [comment]
Hi hanin97, good suggestion！  

Actually, it have supported segmentation **mask** processing in `RandomElastic` and `RandomAffineCV2` transforms class (which transforms on the level of **shape**).     
As for `RandomGaussBlur` and `HEDJitter` class, it only transforms on **color** level so the corresponding mask is not required to handle.    

By the way, i just fixed `RandomAffineCV2` class. We should pass `Args: mask` with `Args: img` to `__call__()` function rather than `__init__()` func.     

Have fun!
